spring.application.name=backend

# ==============================
# SERVER
# ==============================
server.port=8080
server.servlet.context-path=/api

# ==============================
# DATABASE - PostgreSQL
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5432/carteira_produtor
spring.datasource.username=postgres
spring.datasource.password=luiz
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool de conexões (melhora performance)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# ==============================
# JPA / HIBERNATE
# ==============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Manaus

# Evita erro de Lazy initialization
spring.jpa.open-in-view=false

# ==============================
# JWT
# ==============================
jwt.secret=chave-super-secreta-com-no-minimo-32-caracteres
jwt.expiration=86400000

# ==============================
# FILE UPLOAD
# ==============================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ==============================
# CORS
# ==============================
cors.allowed-origins=http://localhost:3000